### ISSUE TITLE
Allow users to View,but not edit, other users' Private Exhibits

### ISSUE THREAD

**Issue by rootl** [ebellempire/MoreUserRoles#1]
Greetings,

I really appreciate your MoreUserRoles plugin. I have been able to add additional roles and custom permissions with this plugin.  

One role/permission combination that I cannot figure out is this:  The ability to view others' private exhibits, but only be able to edit or delete the users' own private or public exhibits (self).   I have tried inheriting from Contributor. I have tried inheriting from Admin and denying edit abilities.    Any advice would be appreciated and absolutely acknowledged.  

Thank you kindly.

**Comment by ebellempire** [comment]
Try something like this maybe?

Untested:

```
$acl->allow('author','ExhibitBuilder_Exhibits',array('browse','show')); // allow author to view all exhibits        

$acl->allow('editor','ExhibitBuilder_Exhibits',array('editAll','deleteAll')); // allow editor to edit and delete exhibits
```

**Comment by rootl** [comment]
Thank you very much! I finally succeded in creating the role and permissions I needed. 'ExhibitBuilder_Exhibits' was they key. Thank you again.  Code is below.  

$acl->addRole(new Zend_Acl_Role('studentContributor'), 'contributor');  
 $acl->allow('studentContributor','ExhibitBuilder_Exhibits',array('browse','show'));  
$acl->allow('studentContributor', array('Items', 'Collections','ExhibitBuilder_Exhibits', 'ElementSets', 'Elements','Search'), 'showNotPublic');
