### ISSUE TITLE
Letting Editor role browse for other user's Items

### ISSUE THREAD

**Issue by DBinaghi** [ebellempire/MoreUserRoles#2]
Hi.
It seems that there's one function missing for the Editor's role: when browsing for Items, cannot choose their owner, so cannot easily find other user's Items, although it's allowed to edit them.
So, I suggest this extra function could be added by editing the correspondent ACL line:

```
$acl->allow('editor','Users',array('browse'));
```

Hope this helps.

**Comment by ebellempire** [comment]
Thanks, this is now in the master branch.
https://github.com/ebellempire/MoreUserRoles/commit/762724a576493b9b2d3d0120cf24c23aaa05411b
