### ISSUE TITLE
Can editors publish all Items?

### ISSUE THREAD

**Issue by DBinaghi** [ebellempire/MoreUserRoles#4]
Hi.

First of all, thanks for the plugin.
Double checking: are **Editors** allowed to make Public any Item, or just their own? It seems to me the plugin description is wrong about it.

My 2 cents.

**Comment by ebellempire** [comment]
Authors can only publish their own items. Editors can publish any items.

- Authors [inherit the rights](https://omeka.org/classic/docs/Admin/Users/#user-levels-and-access) of Contributors but are able to publish their own items.
- Editors [inherit the rights](https://omeka.org/classic/docs/Admin/Users/#user-levels-and-access) of Authors but are able to edit and delete Items and Files created by other users and make items Featured.

**Comment by DBinaghi** [comment]
Sorry, my bad: I meant Editors, not Authors (as correctly written in the title). It seems that Editors can make all Items Public, not just theirs, so in that case the instructions would be misleading.

**Comment by ebellempire** [comment]
I might be missing something but the description seems correct to me. Authors can create/edit/publish their own items. Editors inherit the rights of Authors, so they too can create/edit/publish their own items, but also have additional rights (i.e. they can edit/publish items created by other users and decide which items are featured). I guess maybe you're suggesting that the description should say editors can "make items Featured _and Public_?"

**Comment by DBinaghi** [comment]
Yes: if that's confirmed (I didn't know whether it was your first intention or not; I personally find it useful), then "_and Public_" should be added, otherwise it seems the inherited ability is just to publish one own's Item.

Incidentally: have you seen the forks created by some other users? Maybe those extras could be included in your plugin, with an added config form to let admin choose which ones to enable and which one not. (just an idea).

Again: thanks for the useful plugin.

**Comment by ebellempire** [comment]
addressed by https://github.com/ebellempire/MoreUserRoles/commit/fb07883a89357e5328532b56079fac9d495ba3ad
